---

- name: "{{ user_mode }} | user_groups"
  when: user_groups is defined
  block:
    - name: "{{ user_mode }} | user_groups is iterable"
      ansible.builtin.assert:
        that: user_groups is iterable
        quiet: true

    - name: "{{ user_mode }} | group.name "
      ansible.builtin.assert:
        that:
          - item.name is defined
          - item.name is string
        quiet: true
      loop: "{{ user_groups }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "{{ user_mode }} | group.state "
      when: item.state is defined
      ansible.builtin.assert:
        that:
          - item.state is string
          - item.state in [ "absent", "present" ]
        quiet: true
      loop: "{{ user_groups }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "{{ user_mode }} | group.gid "
      when: item.gid is defined
      ansible.builtin.assert:
        that:
          - item.gid is number
          - item.gid > 0
        quiet: true
      loop: "{{ user_groups }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "{{ user_mode }} | group.system "
      when: item.system is defined
      ansible.builtin.assert:
        that:
          - item.system is boolean
        quiet: true
      loop: "{{ user_groups }}"
      loop_control:
        label: "{{ item.name }}"

- name: "{{ user_mode }} | user_users"
  when: user_users is defined
  block:
    - name: "{{ user_mode }} | user_users is iterable"
      ansible.builtin.assert:
        that: user_users is iterable
        quiet: true

    - name: "{{ user_mode }} | user.name "
      ansible.builtin.assert:
        that:
          - item.name is defined
          - item.name is string
        quiet: true
      loop: "{{ user_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "{{ user_mode }} | user.state "
      when: item.state is defined
      ansible.builtin.assert:
        that:
          - item.state is string
          - item.state in [ "absent", "present" ]
        quiet: true
      loop: "{{ user_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "{{ user_mode }} | user.uid "
      when: item.uid is defined
      ansible.builtin.assert:
        that:
          - item.uid is number
          - item.uid >= 0
        quiet: true
      loop: "{{ user_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "{{ user_mode }} | user.system "
      when: item.system is defined
      ansible.builtin.assert:
        that:
          - item.system is boolean
        quiet: true
      loop: "{{ user_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "{{ user_mode }} | user.comment "
      when: item.comment is defined
      ansible.builtin.assert:
        that:
          - item.comment is string
        quiet: true
      loop: "{{ user_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "{{ user_mode }} | user.create_home "
      when: item.create_home is defined
      ansible.builtin.assert:
        that:
          - item.create_home is boolean
        quiet: true
      loop: "{{ user_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "{{ user_mode }} | user.group "
      when: item.group is defined
      ansible.builtin.assert:
        that:
          - item.group is string
        quiet: true
      loop: "{{ user_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "{{ user_mode }} | user.groups "
      when: item.groups is defined
      ansible.builtin.assert:
        that:
          - item.groups is string
        quiet: true
      loop: "{{ user_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "{{ user_mode }} | user.home "
      when: item.home is defined
      ansible.builtin.assert:
        that:
          - item.home is string
        quiet: true
      loop: "{{ user_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "{{ user_mode }} | user.shell"
      when: item.shell is defined
      ansible.builtin.assert:
        that:
          - item.shell is string
        quiet: true
      loop: "{{ user_users }}"
      loop_control:
        label: "{{ item.name }}"
