---

name: MOLECULE LINT

on:
  push:
  pull_request:
  workflow_call:

jobs:
  yaml-lint:
    uses: buissetemmanuel/cicd-templates/.github/workflows/yamllint.yml@v1.1.2
  ansible-lint:
    uses: buissetemmanuel/cicd-templates/.github/workflows/ansible-lint.yml@v1.1.2
